### PR TITLE
Updated node

### PR DESCRIPTION
**Pull request by amanda11**
Testing the build as part of investigating nodejs upgrade

### CODE REVIEW

**Comment by arm4b** [comment]
Node version requirements are defined in the deb/rpm package specs:


https://github.com/StackStorm/st2chatops/blob/dc4bd38cc8b42316c1e21553c65144fb79d2751d/rpm/st2chatops.spec#L11
https://github.com/StackStorm/st2chatops/blob/dc4bd38cc8b42316c1e21553c65144fb79d2751d/debian/control#L14

Next, `package.json`
https://github.com/StackStorm/st2chatops/blob/dc4bd38cc8b42316c1e21553c65144fb79d2751d/package.json#L27-L29

And good news, looks like in `hubot-stackstorm` which is a core component of st2 chatops solution,
looks like we already test with nodejs `12`: https://github.com/StackStorm/hubot-stackstorm/blob/48eccfdbcbc5e3f72d2dbe8c366bd5648207ef50/.travis.yml#L10 (https://travis-ci.org/github/StackStorm/hubot-stackstorm/builds/548411849)

Hopefully @blag could help with the pointers more.

**Comment by amanda11** [comment]
Build passed. Not yet tried the package in a node > 10 environment.

**Comment by amanda11** [comment]
When built against node 10, and installed on a ST2 using node 14 and connected to slack - ran initial tests ok.
When built against node 14 (As per last commit) and installed on ST2 using node 14, got authorisation issues connecting to slack. Not been able to track down why.

**Comment by amanda11** [comment]
Merged latest changes in, and re-built dependencies.
Manual isntall of ST2 on EL8 with node 14. Put in place artifact from this build and tested against live slack - all ok.

**Review by blag — APPROVED** [review]

**Pull request merged**
