### PR TITLE
Update npm-shrinkwrap.json with new hubot-stackstorm

### PR DESCRIPTION
**Pull request by blag**
Follow-up to https://github.com/StackStorm/st2chatops/pull/127 which missed npm-shrinkwrap.json update

### CODE REVIEW

**Comment by arm4b** [comment]
Yeah, there is a way to regenerate shrinkwrap with minimal changes, not all possible deps. Otherwise that diff will break things.

**Comment by blag** [comment]
The `babel-eslint` package has somehow snuck into `packages.json`, and subsequently into this `npm-shrinkwrap.json` when I updated it. I'm pretty sure that `babel-eslint` should go in the `devDependencies` section instead. That should (I think) drastically reduce the size of this diff once I regenerate `npm-shrinkwrap.json`.

@armab @LindsayHill @m4dcoder Any objections?

**Comment by arm4b** [comment]
Yeah, finally found #104 where we documented `npm-shrinkwrap` update process with minimal diff.
Pushed https://github.com/StackStorm/st2chatops/pull/128/commits/3f3dcaec9290d8f524d72679bd2b210b3e7a7b97 that should do it.

**Review by arm4b — APPROVED** [review]
:+1:

**Pull request merged**
