### PR TITLE
Update dependency for hubot-xmpp

### PR DESCRIPTION
**Pull request by sergiik**
HUBOT_XMPP_PREFERRED_SASL_MECHANISM env variable doesn't work for old 0.1.18 version so let's update it to the newest one where it works.

### CODE REVIEW

**Review by arm4b — CHANGES_REQUESTED** [review]
Makes sense,

need to also re-generate the `npm-shrinkwrap.json` based on new changes.

**Comment by sergiik** [comment]
I updated npm-shrinkwrap.json.
There are a lot of changes though because it wasn't updated for a long time plus the structure with newer npm is different as it tries to keep dependency tree as flat as possible.

**Comment by sergiik** [comment]
Reworked it inside st2chatops_xenial docker with npm 3.10.10

**Review by arm4b — APPROVED** [review]
Thanks! Looks good :+1: 

Hopefully it won't break anything else :)

**Pull request merged**
