### PR TITLE
NPM json after install with hubot-stackstorm updated [WIP]

### PR DESCRIPTION
**Pull request by amanda11**

### CODE REVIEW

**Comment by amanda11** [comment]
Updated package.json to have newer hubot-stackstorm, and then performed npm install --production.
shrinkwrap not run...

**Review by blag — APPROVED** [review]
This looks good to me. @armab Please confirm.

**Comment by amanda11** [comment]
@blag I'm not happy. The resulting st2chatops package that gets built uses lodash earlier than the verison specified in hubot-stackstorm. So I think the shrinkwrap is necessary...

**Comment by amanda11** [comment]
Gone back to https://github.com/StackStorm/st2chatops/pull/164 - I think that PR is closer to being the right one. It was created from the docker examples and then remove the package that gets installed by the preinstall.

Leaving this for reference, in case need to come back to it...

**Comment by amanda11** [comment]
As #164 working and dependencies updating, closing this and not merging...

**Pull request closed without merging**
