### PR TITLE
Comment out slack

### PR DESCRIPTION
**Pull request by dzimine**
Comment out slack adapter as there's no good defaults. Service will continue to work.

This will need a correspondent change in https://github.com/StackStorm/st2-packages/pull/206/files cc @lakshmi-kannan to uncomment the lines.

Longer term, I'd like to ask @emedvedev to add all supported Chat Adapter's environment variables, commented out, so that user (or script) can uncomment them for a given provider.

### CODE REVIEW

**Comment by emedvedev** [comment]
Ack.

**Comment by enykeev** [comment]
I've fixed tests on this one, but bootstrap scripts are also need to be changed. Do we really care that much about this lines to go into the hassle of changing it in two repo, backporting it to stable and then testing it still works everywhere?

**Comment by emedvedev** [comment]
Added the adapter blocks as well as the doc links for each one.

**Comment by lakshmi-kannan** [comment]
> I've fixed tests on this one, but bootstrap scripts are also need to be changed. Do we really care that much about this lines to go into the hassle of changing it in two repo, backporting it to stable and then testing it still works everywhere?

That was my question too but sometimes @dzimine is insistent on such things. Can you merge to 1.3 as well?

**Pull request merged**
