### PR TITLE
Add files for building from Rocky8

### PR DESCRIPTION
**Pull request by amanda11**
Move building of st2chatops for el8 from centos8 to rocky8.

Part of StackStorm/community#88

### CODE REVIEW

**Comment by amanda11** [comment]
Ready for review, but would like to hold out on merge until the st2-packages corresponding PR is ready...

**Review by arm4b — COMMENTED** [review]
Considering `rockylinux` is replacing `centos8` for the build, I think there's also a need to remove the inactive centos8 Dockerfiles to avoid confusion in the future

https://github.com/StackStorm/st2chatops/tree/master/packagingenv
https://github.com/StackStorm/st2chatops/tree/master/testingenv

**Comment by amanda11** [comment]
> Considering `rockylinux` is replacing `centos8` for the build, I think there's also a need to remove the inactive centos8 Dockerfiles to avoid confusion in the future
> 
> https://github.com/StackStorm/st2chatops/tree/master/packagingenv https://github.com/StackStorm/st2chatops/tree/master/testingenv

Removed them (unfortunate side affect git diff reports them as a move from centos8 to rockylinux8 - but was an add and a delete...)

**Review by arm4b — APPROVED** [review]
Thanks a lot! :+1:

**Review by cognifloyd — APPROVED** [review]

**Comment by cognifloyd** [comment]
> Ready for review, but would like to hold out on merge until the st2-packages corresponding PR is ready...

Both of the other PRs have been merged. Merging.

**Comment by amanda11** [comment]
@cognifloyd Thanks for merge - wasn't online when the changes got approved!

**Pull request merged**
