### PR TITLE
Fix version for the 1.3.2 release

### PR DESCRIPTION
**Pull request by m4dcoder**

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
should wait for a +1 from @enykeev to be absolutely certain we’d generate 1.3.2 packages with same code as current 1.3.0. cc: m4dcoder

**Comment by enykeev** [comment]
@lakshmi-kannan Quite frankly, I don't see what might go wrong, our dependencies are pinned with shrinkwrap and we build new packages on every push to the branch so new 1.3.2 package should be exactly the same as an old 1.3.0 one. We can go an extra mile and diff them if you're worried. Any thing in particular that bothers you?

**Comment by enykeev** [comment]
Oh well, seems like I did indeed missed something =)

```
$ pkgdiff ~/Downloads/st2chatops_1.3.0-6_amd64.deb ~/Downloads/st2chatops_1.3.2-1_amd64.deb
reading packages ...
comparing packages ...
creating changes report ...
result: CHANGED (0.03%)
see detailed report:
  pkgdiff_reports/st2chatops/1.3.0-6_to_1.3.2-1/changes_report.html
```

Full report is [here](http://cloud.mech.sh/1r1x3i3O0R0c) if you're interested.

The bottom line is that build tool `node-gyp` has updated since then so the paths to it have changed around all the dependencies. Nothing to worry about, I'd say, I don't see any crucial changes.

**Comment by m4dcoder** [comment]
Can I merge this?

**Pull request merged**
